server:
  port: 8083

spring:
  application:
    name: EMS-API
  datasource:
    url: jdbc:mysql://localhost:3306/EMS
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
        